name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.7.0

      - name: Push Docker image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/labmanagefront:${{ github.sha }}

      - name: Update server to use latest Docker image
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.IP_ADDRESS }}
          username: ${{ secrets.SERVER_NAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/labmanagefront:${{ github.sha }}
            docker stop labmanagefront || true && docker rm labmanagefront || true
            docker run -d --name=labmanagefront -p 10025:3000 ${{ secrets.DOCKER_USERNAME }}/labmanagefront:${{ github.sha }}

